// <auto-generated />
using System;
using E_Commerce.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Context.Migrations
{
    [DbContext(typeof(E_CommerceContext))]
<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
    [Migration("20240120153323_InitModel")]
    partial class InitModel
========
    [Migration("20240125053558_initial")]
    partial class initial
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
            modelBuilder.Entity("CartCartItem", b =>
                {
                    b.Property<int>("CartDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("cartId")
                        .HasColumnType("int");

                    b.HasKey("CartDetailsId", "cartId");

                    b.HasIndex("cartId");

                    b.ToTable("CartCartItem");
                });

========
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
            modelBuilder.Entity("E_Commerce_Project.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("cartID")
                        .HasColumnType("int");

                    b.Property<int>("productID")
                        .HasColumnType("int");
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("cartID");

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    b.HasIndex("UserId");
========
                    b.HasIndex("productID");
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NoOfProducts")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("UserID")
                        .HasColumnType("int");
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
            modelBuilder.Entity("E_Commerce_Project.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
========
            modelBuilder.Entity("E_Commerce_Project.Models.OrderItems", b =>
                {
                    b.Property<int>("id")
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
========
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("OrderId");

                    b.HasIndex("productId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("categoryID")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("categoryID");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

========
                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CartCartItem", b =>
                {
                    b.HasOne("E_Commerce_Project.Models.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Project.Models.CartItem", null)
                        .WithMany()
                        .HasForeignKey("cartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Cart", b =>
                {
                    b.HasOne("E_Commerce_Project.Models.Product", null)
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.CartItem", b =>
                {
<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    b.HasOne("E_Commerce_Project.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Project.Models.User", null)
                        .WithMany("Carts")
                        .HasForeignKey("UserId");
========
                    b.HasOne("E_Commerce_Project.Models.Cart", "cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("cartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Project.Models.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("productID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Order", b =>
                {
                    b.HasOne("E_Commerce_Project.Models.User", "User")
<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
========
                        .WithMany("orders")
                        .HasForeignKey("UserID")
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
            modelBuilder.Entity("E_Commerce_Project.Models.OrderItem", b =>
                {
                    b.HasOne("E_Commerce_Project.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
========
            modelBuilder.Entity("E_Commerce_Project.Models.OrderItems", b =>
                {
                    b.HasOne("E_Commerce_Project.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Project.Models.Product", "product")
                        .WithMany("OrderItems")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("product");
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Product", b =>
                {
                    b.HasOne("E_Commerce_Project.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Project.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Order", b =>
                {
<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    b.Navigation("Products");
========
                    b.Navigation("OrderItems");
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
                });

            modelBuilder.Entity("E_Commerce_Project.Models.Product", b =>
                {
                    b.Navigation("CartDetails");
<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
========

                    b.Navigation("OrderItems");
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs
                });

            modelBuilder.Entity("E_Commerce_Project.Models.User", b =>
                {
<<<<<<<< HEAD:E-Commerce.Context/Migrations/20240120153323_InitModel.Designer.cs
                    b.Navigation("Carts");
========
                    b.Navigation("Cart");
>>>>>>>> last_condition_for_All:E-Commerce.Context/Migrations/20240125053558_initial.Designer.cs

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
